import type { ScenarioInput, WizardState } from './types';

export const DEFAULT_SCENARIOS: ScenarioInput[] = [
  {
    id: 'scenario-1',
    lenderName: 'Bank of Ireland',
    housePrice: 400000,
    otherFees: 5000,
    loanToValue: 0.80,
    otherFeesCoveredByDebt: false,
    mortgageTerm: 30,
    rateStructure: 'fixed',
    fixedRate: 0.038,
    fixedPeriodYears: 5,
    variableRate: 0.042,
    repaymentType: 'annuity',
    overpaymentReduces: 'term',
  },
  {
    id: 'scenario-2',
    lenderName: 'AIB',
    housePrice: 400000,
    otherFees: 5000,
    loanToValue: 0.80,
    otherFeesCoveredByDebt: false,
    mortgageTerm: 30,
    rateStructure: 'tracker',
    trackerBaseRate: 0.026,
    trackerMargin: 0.014,
    variableRate: 0.040,
    repaymentType: 'annuity',
    overpaymentReduces: 'term',
  },
  {
    id: 'scenario-3',
    lenderName: 'Permanent TSB',
    housePrice: 400000,
    otherFees: 5000,
    loanToValue: 0.80,
    otherFeesCoveredByDebt: false,
    mortgageTerm: 30,
    rateStructure: 'fixed',
    fixedRate: 0.0365,
    fixedPeriodYears: 3,
    variableRate: 0.042,
    repaymentType: 'annuity',
    overpaymentReduces: 'term',
  },
  {
    id: 'scenario-4',
    lenderName: 'Haven',
    housePrice: 400000,
    otherFees: 5000,
    loanToValue: 0.80,
    otherFeesCoveredByDebt: false,
    mortgageTerm: 30,
    rateStructure: 'fixed',
    fixedRate: 0.041,
    fixedPeriodYears: 10,
    variableRate: 0.042,
    repaymentType: 'annuity',
    overpaymentReduces: 'term',
  },
];

export const DEFAULT_WIZARD_STATE: WizardState = {
  step: 1,
  market: 'IE',
  housePrice: 400000,
  deposit: 80000,
  otherFees: 5000,
  otherFeesCoveredByDebt: false,
  purchaseDate: new Date().toISOString().slice(0, 7),
  buyerType: 'first_time',
  annualIncome: 70000,
  coBorrowerIncome: 0,
  govtSchemeEnabled: false,
  govtSupportAmount: 0,
  selectedGovtSchemeName: null,
  propertyType: 'secondary',
  rateStructure: 'fixed',
  splitFixedProportion: 0.7,
  mortgageTerm: 30,
  paymentHolidayMonths: 0,
  wizardCashbackAmount: 0,
  wizardCashbackClawbackYears: 5,
  scenarios: DEFAULT_SCENARIOS,
  isUnlocked: false,
};
